# Generated by Django 5.2 on 2025-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_offer_created_at_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
