# Generated by Django 5.2.5 on 2025-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=25)),
                ('tel', models.CharField(default='', max_length=15)),
                ('description', models.TextField(default='', max_length=255)),
                ('working_hours', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
