# Generated by Django 5.2 on 2025-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='original_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
